const bookings = [
  {
    practitioner: "Dr. Garcia",
    patient: "John Doe",
    type: "Check-up",
    startTime: 9,
    endTime: 10,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Jane Smith",
    type: "Consultation",
    startTime: 10,
    endTime: 11,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "David Kim",
    type: "Follow-up",
    startTime: 11,
    endTime: 12,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Sarah Lee",
    type: "Check-up",
    startTime: 12,
    endTime: 13,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Alex Wong",
    type: "Consultation",
    startTime: 13,
    endTime: 14,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Ava Chen",
    type: "Follow-up",
    startTime: 14,
    endTime: 15,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Emily Chang",
    type: "Check-up",
    startTime: 15,
    endTime: 16,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Jack Liu",
    type: "Consultation",
    startTime: 16,
    endTime: 17,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Sophia Chen",
    type: "Follow-up",
    startTime: 17,
    endTime: 18,
  },
  {
    practitioner: "Dr. Garcia",
    patient: "Noah Kim",
    type: "Check-up",
    startTime: 18,
    endTime: 19,
  },
];
export default { bookings };
